version: '3.8'

services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes

  clickhouse:
    image: 'yandex/clickhouse-server:latest'
    ports:
      - '8123:8123'
      - '9000:9000'

  app:
    build: .
    depends_on:
      - kafka
      - clickhouse
    volumes:
      - .:/app
    command: ["python", "main.py"]





